openapi: 3.0.2
info:
  version: '1.0'
  title: JT OpenApi Course
  termsOfService: http://example.com/terms/
  contact:
    name: John Thompson
    url: https://springframework.guru
    email: john@springframework.guru
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://dev.example.com
  description: Development Server
- url: https://qa.example.com
  description: QA Server
- url: https://prod.example.com
  description: Production Server
paths:
  /v1/customers:
    get:
      responses:
        200:
          description: List of Customers
          content:
            application/json:
              schema:
                maxItems: 100
                minItems: 1
                type: array
                items:
                  maxLength: 100
                  minLength: 2
                  type: object
                  description: Customer Object
                  properties:
                    id:
                      type: string
                      format: uuid
                    firstName:
                      type: string
                      example: Pierrot
                    lastName:
                      type: string
                      example: Mongonnam
                    Address:
                      type: object
                      properties:
                        line1:
                          type: string
                          example: 10 Rue Manga Bell
                        city:
                          type: string
                          example: Douala
                        zipCode:
                          type: string
                          example: 5555
                        stateCode:
                          type: string
                          enum: [OCE,WOU,NDE,SAN,NTE]
  /v1/beers:
    get:
      responses:
        200:
          description: List of Beers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  description: Beer Object
                  properties:
                    beerName:
                      type: string
                    style:
                      type: string
                    upc:
                      type: string
                      enum: [ALE, PALE_ALE, IPA, WHEAT, LAGER]
                    price:
                      type: number
                      format: float
                      example: 25.4
                    qtyOnHand:
                      description: quantity on Hand
                      type: integer
                      format: int32
                      example: 3,450
                    brewery:
                      type: object
                      description: Brewery Object
                      properties:
                        name:
                          type: string
                          example: UCB
                        location:
                          type: string
                          example: Douala-Bonandjo
        404:
          description: No Beers Found
components: {}